# Generated by Django 5.2.7 on 2025-10-16 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="workspace_id",
            new_name="user_id",
        ),
    ]
