# Generated by Django 5.2.7 on 2025-11-06 23:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0002_workspace_is_active_workspace_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "profile_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="none", max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF file"),
                            ("DOCX", "DOCX file"),
                            ("PPTX", "PPTX file"),
                            ("XLSX", "XLSX file"),
                            ("JPG", "JPG file"),
                            ("ZIP", "ZIP file"),
                            ("TXT", "TXT file"),
                        ],
                        max_length=15,
                    ),
                ),
                ("size", models.BigIntegerField()),
                ("uploaded", models.DateTimeField(default=django.utils.timezone.now)),
                ("file", models.FileField(upload_to="")),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="workspaces.workspace",
                    ),
                ),
            ],
        ),
    ]
