# Generated by Django 5.2.7 on 2025-11-16 20:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0004_alter_workspace_invite_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="resources_t_name_352b9c_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "profile_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="none", max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF file"),
                            ("DOCX", "DOCX file"),
                            ("PPTX", "PPTX file"),
                            ("XLSX", "XLSX file"),
                            ("JPG", "JPG file"),
                            ("PNG", "PNG file"),
                            ("ZIP", "ZIP file"),
                            ("TXT", "TXT file"),
                        ],
                        max_length=15,
                    ),
                ),
                ("size", models.BigIntegerField()),
                ("uploaded", models.DateTimeField(default=django.utils.timezone.now)),
                ("file", models.FileField(max_length=200, upload_to="")),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="resources", to="resources.tag"
                    ),
                ),
            ],
        ),
    ]
