# Generated by Django 5.2.7 on 2025-11-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="type",
            field=models.CharField(
                choices=[
                    ("PDF", "PDF file"),
                    ("DOCX", "DOCX file"),
                    ("DOC", "DOC file"),
                    ("PPTX", "PPTX file"),
                    ("PPT", "PPT file"),
                    ("XLSX", "XLSX file"),
                    ("XLS", "XLS file"),
                    ("JPG", "JPG file"),
                    ("JPEG", "JPEG file"),
                    ("PNG", "PNG file"),
                    ("GIF", "GIF file"),
                    ("SVG", "SVG file"),
                    ("BMP", "BMP file"),
                    ("WEBP", "WEBP file"),
                    ("ICO", "ICO file"),
                    ("MP4", "MP4 file"),
                    ("AVI", "AVI file"),
                    ("MOV", "MOV file"),
                    ("WMV", "WMV file"),
                    ("WEBM", "WEBM file"),
                    ("MP3", "MP3 file"),
                    ("WAV", "WAV file"),
                    ("OGG", "OGG file"),
                    ("TXT", "TXT file"),
                    ("CSV", "CSV file"),
                    ("JSON", "JSON file"),
                    ("XML", "XML file"),
                    ("MD", "Markdown file"),
                    ("HTML", "HTML file"),
                    ("CSS", "CSS file"),
                    ("JS", "JavaScript file"),
                    ("PY", "Python file"),
                    ("ZIP", "ZIP file"),
                    ("RAR", "RAR file"),
                    ("TAR", "TAR file"),
                    ("GZ", "GZ file"),
                    ("OTHER", "Other file"),
                ],
                max_length=15,
            ),
        ),
    ]
