# Generated by Django 5.2.7 on 2025-11-07 00:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
        ("workspaces", "0002_workspace_is_active_workspace_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="uploaded_by",
            field=models.ForeignKey(
                default=27,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="workspace",
            field=models.ForeignKey(
                default=uuid.UUID("cdb5abfe-dc99-4394-ac0e-e50a2f21d960"),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to="workspaces.workspace",
            ),
        ),
    ]
