# Generated by Django 5.2.7 on 2025-11-07 23:08

import resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0004_alter_resource_uploaded_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="file",
            field=models.FileField(
                max_length=200, upload_to=resources.models.Resource.resource_upload_to
            ),
        ),
    ]
