# Generated by Django 5.2.7 on 2025-11-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0005_alter_resource_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="resources_t_name_352b9c_idx")
                ],
            },
        ),
        migrations.AddField(
            model_name="resource",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="resources", to="resources.tag"
            ),
        ),
    ]
