# Generated by Django 5.2.7 on 2025-11-10 19:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def migrate_task_data_forward(apps, schema_editor):
    """
    Migrate existing task data to use ForeignKey relationships.
    This function handles the transition from CharField creator/assignee to ForeignKey.
    """
    Task = apps.get_model("tasks", "Task")
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Workspace = apps.get_model("workspaces", "Workspace")

    # Get or create a default user for creator field
    default_user, _ = User.objects.get_or_create(
        id=1,
        defaults={
            "username": "admin",
            "email": "admin@collabdesk.com",
        },
    )

    # Get the default workspace
    default_workspace_id = uuid.UUID("cdb5abfe-dc99-4394-ac0e-e50a2f21d960")
    default_workspace, _ = Workspace.objects.get_or_create(
        workspace_id=default_workspace_id,
        defaults={
            "name": "Default Workspace",
            "description": "Default workspace for migration",
            "created_by": default_user,
        },
    )

    # Update all existing tasks
    for task in Task.objects.all():
        # Set created_by to default user if creator was a string
        if not task.created_by_id:
            task.created_by = default_user

        # Set workspace to default workspace
        if not task.workspace_id:
            task.workspace = default_workspace

        # Handle assignee conversion - set to None if it was an empty string or invalid
        # We'll leave assignee_new as NULL for now (can be updated later by users)

        task.save()


def migrate_task_data_backward(apps, schema_editor):
    """
    Reverse migration - convert ForeignKey back to CharField.
    """
    Task = apps.get_model("tasks", "Task")

    for task in Task.objects.all():
        if task.created_by:
            task.creator_old = task.created_by.username
        if task.assignee_new:
            task.assignee_old = task.assignee_new.username
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
        ("workspaces", "0002_workspace_is_active_workspace_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Add new fields without removing old ones
        migrations.AddField(
            model_name="task",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_tasks",
                to=settings.AUTH_USER_MODEL,
                null=True,  # Temporarily allow null
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="workspace",
            field=models.ForeignKey(
                default=uuid.UUID("cdb5abfe-dc99-4394-ac0e-e50a2f21d960"),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="workspaces.workspace",
                null=True,  # Temporarily allow null
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="assignee_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # Step 2: Migrate the data
        migrations.RunPython(migrate_task_data_forward, migrate_task_data_backward),
        # Step 3: Make created_by and workspace non-nullable
        migrations.AlterField(
            model_name="task",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="workspace",
            field=models.ForeignKey(
                default=uuid.UUID("cdb5abfe-dc99-4394-ac0e-e50a2f21d960"),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="workspaces.workspace",
            ),
        ),
        # Step 4: Remove old fields
        migrations.RemoveField(
            model_name="task",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="task",
            name="assignee",
        ),
        # Step 5: Rename assignee_new to assignee
        migrations.RenameField(
            model_name="task",
            old_name="assignee_new",
            new_name="assignee",
        ),
        # Step 6: Add indexes
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["workspace", "created_at"], name="tasks_task_workspa_3df06e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["created_by", "created_at"],
                name="tasks_task_created_d4df6a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["assignee", "status"], name="tasks_task_assigne_7928f6_idx"
            ),
        ),
    ]
