# Generated by Django 5.2.7 on 2025-11-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "To do"),
                    ("in-progress", "In progress"),
                    ("done", "Done"),
                ],
                default="todo",
                max_length=15,
            ),
        ),
    ]
