# Generated by Django 5.2.7 on 2025-10-11 21:00

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Unavailability",
        ),
        migrations.RemoveField(
            model_name="event",
            name="event_title",
        ),
        migrations.RemoveField(
            model_name="event",
            name="id",
        ),
        migrations.AddField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 10, 11, 21, 0, 12, 757563, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.CharField(default="none", max_length=1000),
        ),
        migrations.AddField(
            model_name="event",
            name="event_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[("INDIVIDUAL", "Individual Event"), ("GROUP", "Group Event")],
                default="GROUP",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(default="none", max_length=100),
        ),
        migrations.AddField(
            model_name="event",
            name="title",
            field=models.CharField(default="none", max_length=100),
        ),
        migrations.AddField(
            model_name="event",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 10, 11, 21, 0, 12, 757573, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
