# Generated by Django 5.2.7 on 2025-11-24 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0004_alter_workspace_invite_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_key",
                    models.CharField(
                        help_text="S3 key (UUID-prefixed filename)", max_length=255
                    ),
                ),
                (
                    "file_name",
                    models.CharField(help_text="Original filename", max_length=255),
                ),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_documents",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="AIConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[("summary", "Summary"), ("plan", "Plan")],
                        help_text="Type of AI action (summary or plan)",
                        max_length=10,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Auto-generated title", max_length=255),
                ),
                ("ai_response", models.TextField(help_text="AI-generated content")),
                (
                    "saved_to_notes",
                    models.BooleanField(
                        default=False, help_text="Whether this has been saved to notes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_conversations",
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="chat.chatdocument",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="chatdocument",
            index=models.Index(
                fields=["user", "workspace", "-uploaded_at"],
                name="chat_chatdo_user_id_93c3f7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiconversation",
            index=models.Index(
                fields=["user", "workspace", "-created_at"],
                name="chat_aiconv_user_id_d80709_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiconversation",
            index=models.Index(
                fields=["document", "action_type"],
                name="chat_aiconv_documen_c0c76a_idx",
            ),
        ),
    ]
