# Generated by Django 4.2.25 on 2025-11-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_auth0_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_id",
        ),
    ]
