# Generated by Django 4.2.25 on 2025-11-14 16:25

from django.db import migrations, models
import uuid


def generate_user_ids(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.all():
        user.user_id = uuid.uuid4()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_id",
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(
            generate_user_ids, 
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(unique=True),
        ),
    ]



    

