# Generated by Django 5.2.7 on 2025-11-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_eventparticipant"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
