# Generated by Django 5.2.7 on 2025-11-02 23:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_event_is_private"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-start_time"]},
        ),
        migrations.RemoveField(
            model_name="event",
            name="workspace_id",
        ),
        migrations.AddField(
            model_name="event",
            name="workspace",
            field=models.ForeignKey(
                default=uuid.UUID("cdb5abfe-dc99-4394-ac0e-e50a2f21d960"),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["workspace", "start_time"],
                name="events_even_workspa_677642_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["created_by", "start_time"],
                name="events_even_created_b9750e_idx",
            ),
        ),
    ]
