# Generated by Django 5.2.7 on 2025-11-20 18:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_alter_event_options_remove_event_workspace_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(
                blank=True,
                related_name="events_attending",
                through="events.EventParticipant",
                through_fields=("event", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
