# Generated by Django 5.2.7 on 2025-11-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_event_attendees"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventparticipant",
            name="responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eventparticipant",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("tentative", "Tentative"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
