# Generated by Django 5.2.7 on 2025-11-17 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messageboard", "0001_initial"),
        ("workspaces", "0004_alter_workspace_invite_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="workspace",
            field=models.ForeignKey(
                default="cdb5abfe-dc99-4394-ac0e-e50a2f21d960",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="workspaces.workspace",
            ),
        ),
    ]
