# Generated by Django 5.2.7 on 2025-11-17 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messageboard", "0002_message_workspace"),
        ("workspaces", "0004_alter_workspace_invite_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="workspaces.workspace",
            ),
        ),
    ]
