# Generated by Django 5.2.7 on 2025-11-20 18:04

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messageboard", "0003_alter_message_workspace"),
        ("workspaces", "0004_alter_workspace_invite_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["content"],
                name="message_content_gin_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
