# Generated by Django 5.2.7 on 2025-11-20 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messageboard", "0004_message_message_content_gin_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="message",
            name="message_content_gin_idx",
        ),
    ]
