# Generated by Django 4.2.25 on 2025-11-15 16:35

from django.db import migrations, models
import workspaces.models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0002_workspace_is_active_workspace_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="invite_code",
            field=models.CharField(
                default=workspaces.models.generate_invite_code,
                editable=False,
                max_length=8,
            ),
        ),
    ]
