# Generated by Django 4.2.25 on 2025-11-15 17:02

from django.db import migrations, models
import workspaces.models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0003_workspace_invite_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="invite_code",
            field=models.CharField(
                default=workspaces.models.generate_invite_code,
                editable=False,
                max_length=8,
                unique=True,
            ),
        ),
    ]
