# Generated by Django 4.2.25 on 2025-12-12 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_noteshare"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NoteShare",
        ),
    ]
